function [polynomial] = vandermonde(orderedPairs)
%VandermondeMATRIX takes a matrix of ordered pairs and returns an evaluable Vandermonde polynomail in the form of Horner's nested evaluation scheme

%split pairs on ts and ys
n = length(orderedPairs);
ts = orderedPairs(:,1);
ys = orderedPairs(:,2);

%build a Vandermonde matrix from the ts
A = zeros(n);
for i=1:n
    for j=1:n
        if j == 1
            A(i,j) = 1;
        else
            A(i,j) = ts(i).^(j-1);
        end
    end
end

%solve system of equations generated by the Vandermonde matrix
%must be lsqr becuase matrix here is nearly singular
display(cond(A));
coeffs = lsqr(A, ys, 1e-10, 500);

%Horner's nested eval
polyString = "" + coeffs(1);
endParens(n-2) = "";
for i=1:n-2
    polyString = polyString + " + t*(" + coeffs(i+1);
    endParens(i) = ")";
end
polyString = polyString + " + t*" + coeffs(i+2) + sprintf('%s', endParens);

%return evaluable polynomial
polynomial = inline(polyString, "t");
end

